---

- block:

    - name: ensure apt keyring directory
      ansible.builtin.file:
        path: "{{ apt_keyring_directory }}"
        state: directory
        owner: 'root'
        group: "{{ root_group }}"
        mode: '0755'

    - name: download Docker GPG key
      ansible.builtin.get_url:
        url: "{{ docker_gpg_key_url }}"
        dest: "{{ apt_keyring_directory }}/{{ docker_gpg_key_filename }}"
        mode: '0644'


    - name: add Docker repository
      ansible.builtin.apt_repository:
        repo: "{{ docker_repository_apt_defintion }}"
        state: present
        filename: "{{ docker_repository_apt_filename }}"

    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      changed_when: no

  when: ansible_pkg_mgr == 'apt'
