---

- include_tasks: clean_legacy.yml

- include_tasks: zfs.yml

- include_tasks: apt_repository.yml

- include_tasks: install.yml

- include_tasks: configure.yml

- include_tasks: service.yml

- include_tasks: permission.yml
