---

- block:
    - include_tasks: context.yml

    - include_tasks: docker.yml

  when:
    - want_docker
    - ansible_system == 'Linux'

- name: set has_docker
  set_fact:
    has_docker: "{{ want_docker and ansible_system == 'Linux' }}"
