---

- name: set has_docker to false (default)
  set_fact:
    has_docker: false

- include_tasks: context.yml

- block:
    - include_tasks: docker.yml

    - name: set has_docker to true
      set_fact:
        has_docker: true
  when:
    - want_docker
    - ansible_system == 'Linux'
