---

- name: ensure Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  register: t_workstation_docker_service

- name: restart Docker service on change
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: yes
  when:
    - t_docker_conf_daemon.changed or t_docker_zfs_dataset.changed or t_docker_zfs_mount.changed
    - not t_workstation_docker_service.changed
